version: "3.7"
services:
    mongo:
        image: mongo
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/var/log/mongodb/mongodb.log
        volumes:
            - "mongodbdata:/data/db"
        ports:
            - "27017:27017"
        expose:
            - 27017
        command: "mongod"
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/mern_stack
        ports:
            - "3000:3000"
            - "5000:5000"
        expose:
            - "5000"
        depends_on:
            - mongo
        links:
            - mongo
        command: ["npm", "run", "dev"]
volumes:
  mongodbdata:
    external: true